format_version: v1.0
configName: SAME51NANO_curiosity
folderName: SAMNANOE51
frameworkPath: C:\Users\14073\.mcc
processor: ATSAME51J20A
projectName: SAMNANOE51
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME51_DFP\3.6.130\atdf\ATSAME51J20A.atdf
